TestFaker/Models/ErrorViewModel.cs
namespace TestFaker.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TestFaker/Models/UserDataDisplayModel.cs
namespace TestFaker.Models;

public class UserDataDisplayModel
{
    public Guid Id { get; set; }
    public string? LastName { get; set; }
    public string? FirstName { get; set; }
    public string? Address { get; set; }
    public string? Phone { get; set; }
}

TestFaker/Controllers/CultureController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace TestFaker.Controllers;

public class CultureController : Controller
{
    [HttpPost]
    public IActionResult SetCulture(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(30) }
        );
        Response.Cookies.Append("locale", $"{culture}");
        return LocalRedirect(returnUrl);
    }
}

TestFaker/Controllers/HomeController.cs
using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Newtonsoft.Json;
using TestFaker.Models;
using TestFaker.Service.IService;

namespace TestFaker.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IDataService _service;
    private const int Size = 20;
    private static int SeedValue;
    private static int oldSeed = 0;
    private static int newSeed = 0;
    private static double oldErrorAmount = 5;

    public HomeController(ILogger<HomeController> logger, IDataService service)
    {
        _logger = logger;
        _service = service;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult _TestData(string errorAmount, int seed)
    {
        if (seed != 0)
            newSeed = seed;
        double errorsAmount = double.Parse(errorAmount, CultureInfo.InvariantCulture.NumberFormat);
        if (errorsAmount == 5)
        {
            errorsAmount = oldErrorAmount;
        }else if (errorsAmount != 5)
        {
            oldErrorAmount = errorsAmount;
        }
        if (newSeed == oldSeed)
        {
            SeedValue += 10;
        }else if (newSeed != oldSeed)
        {
            SeedValue = newSeed+10;
        }
        
        var model = _service.GetData(Size, Request.Cookies["locale"], errorsAmount, SeedValue);
        if (model.Count() == 0) return StatusCode(204);
        return PartialView(model);
    }


    public IActionResult Privacy()
    {
        return View();
    }
    
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TestFaker/Views/Home/Index.cshtml
@model List<TestFaker.Models.UserDataDisplayModel>
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization

<input name="errorAmountSlider" id="errorAmountSlider" type="range" value="5" min="0" max="10" step="0.25" class="slider" onkeyup='saveValue(this);' onchange="updateInput(this.value,'errorAmount');">
<input class="slider" type="text" name="errorAmount" id="errorAmount" value="5" onkeyup='saveValue(this);' onchange="updateInput(this.value,'errorAmountSlider');">
<label> Seed: </label>
<input type="text" name="seed" id="seed" value="0" onkeyup='saveValue(this);'>
<button id="butt" class="btn btn-default" onclick="TFun()">Random</button>

<table id="anyTable" class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>@Localizer["Id"]</th>
        <th>@Localizer["First name"]</th>
        <th>@Localizer["Last name"]</th>
        <th>@Localizer["Address"]</th>
        <th>@Localizer["Phone"]</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section Scripts {
    <script src="~/js/InfinitiySroll.js"></script>

    <script>
    var seed = document.getElementById('seed').value;
    var errorAmount = document.getElementById('errorAmountSlider').value;
        var infinityScroll = new InfinitiySroll("anyTable", "/home/_TestData", { errorAmount: errorAmount, seed: seed });
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script>


        function updateInput(val, id) {
            document.getElementById(id).value = val;
            var seed = document.getElementById('seed').value;
            location.reload();
            $.ajax({
                url: "/Home/_TestData",
                method: 'post',
                data: { errorAmount: val, seed: seed },
            });

        }
    </script>

    <script>
        function TFun() {
            var seed = document.getElementById('seed').value;
            var errorAmount = document.getElementById('errorAmountSlider').value;
            $.ajax({
                url: "/Home/_TestData",
                method: 'post',
                data: { errorsAmount: errorAmount, seed: seed }
            });
            location.reload();

        }
    </script>

    <script type="text/javascript">
        document.getElementById("seed").value = getSavedValue("seed");    
        document.getElementById("errorAmount").value = getSavedValue("errorAmount");
        document.getElementById("errorAmountSlider").value = getSavedValue("errorAmount");

        function saveValue(e) {
            var id = e.id;  
            var val = e.value; 
            localStorage.setItem(id, val);
        }

        function getSavedValue(v) {
            if (!localStorage.getItem(v)) {
                return "";
            }
            return localStorage.getItem(v);
        }
    </script>
}

TestFaker/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.Extensions.Options
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestFaker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestFaker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestFaker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();

    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) 
        ? "~/" 
        : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div>
    <form asp-controller="Culture" asp-action="SetCulture" asp-route-returnUrl="@returnUrl" 
          class="form-horizontal nav-link text-dark">
          <select name="culture" 
                onchange="this.form.submit();" 
                asp-for="@requestCulture.RequestCulture.UICulture.Name" 
                asp-items="cultureItems">
          </select>
    </form>
</div>








@{
    ViewData["Title"] = "Home Page";
    var i = 0;
}
                    </ul>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestFaker/Views/Shared/_TestData.cshtml
@model IEnumerable<TestFaker.Models.UserDataDisplayModel>
@{ int i = 0; }
@foreach (var item in Model)
{
    i++;
    <tr>
        <td>
           @i
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
    </tr>
}